### PR TITLE
Fix PDF build

### PR DESCRIPTION
**Pull request by demiankatz**
This PR is designed to fix the project so that `make latexpdf` generates a properly-formatted PDF version of the book that we can use as part of an official release.

TODO
- [x] Remove duplicate "CONTENTS" header
- [x] Eliminate the "CHAPTER ONE," "CHAPTER TWO," etc., large headings at the top of each section, because they are numbered inconsistently with the in-text PART numbers. (Or, if we can figure out how to leave the PREFACE unnumbered, and switch "CHAPTER" to "PART" in the auto-generated headings, that might help too).
- [x] Fix duplicate numbering -- currently, autogenerated section numbers are conflicting with in-text section numbers, resulting in things like "2.1.2 1.1 What is (and isn't) VuFind?".
- [x] Make sure headers and footers contain appropriate information.
- [x] Double-check that HTML version is still valid once PDF meets requirements.

Deferred TODO (out of scope for now)

- Fix internal hard-coded section number cross-references; is there a way to replace these with auto-generated numbers, so if we expand/reorganize the document in future, they will update correctly?

### CODE REVIEW

**Comment by lahmann** [comment]
@demiankatz, I was able to fix the chapter numbering by experimenting with Latex settings. What's still missing is to remove the "Chapter ." section in the footer. I had no success in addressing the footer and changing it. I tried several way including explicitly using the Latex package `fancyhdr` (which is supposed to be used anyway) and redefining the footer as e.g. shown here: https://texblog.org/2007/11/07/headerfooter-in-latex-with-fancyhdr/
Sphinx is supposed to use the `fancyhdr` package for Latex by default but the documentation is not helpful at all regarding the footer (https://www.sphinx-doc.org/en/master/latex.html). I have to continue another day for now I'm stuck - maybe you have an idea how to customize the footer...
But apart from that I think the pdf layout looks good and as I only worked with Latex commands this does not have any effect on html-output.

**Comment by demiankatz** [comment]
Thanks, @lahmann, this is great progress! I probably won't have time to look at this until next week, but I'll see if I can find some time there to move forward with the footer adjustments.

**Comment by demiankatz** [comment]
I just took a look at the updated PDF output, and this is indeed a significant step forward. Thanks again! I haven't had much time to investigate the footer yet, but I did run across [this thread](https://stackoverflow.com/questions/42787445/customize-headers-and-footers-in-latex-using-sphinx) and wonder if it might contain anything helpful. Did you already see that one?

In the meantime, I notice that some of the styling of code snippets seems off, so I'm going to see if I can do anything to fix that in the few minutes that remain for me today.

**Comment by demiankatz** [comment]
The code snippet issue seemed out of scope for this PR, so I opened #2 to address it. It looks like there were some whitespace issues in snippets too. I tried to fix everything, but if anybody has time to give it a double-check, I would be grateful!

**Comment by lahmann** [comment]
@demiankatz unfortunately I did not find any time this week to look into this issue. I'll be back on 25th October - if you cannot manage to peek into this issue until then, I'll take over again. :)

**Comment by demiankatz** [comment]
Thanks, @lahmann, I'll see what I can do next week and will keep you posted!

**Comment by demiankatz** [comment]
@lahmann, I think I've done it! See commits 9c77616 and e5fbc8c -- I first discovered how to clear out the footers, and then I adjusted them so that we put the chapter name on both even and odd pages, instead of having inappropriate information on odd pages. If you agree that this is acceptable, I think we can merge this and release the book. While I would like to eventually find a better way to handle cross-references, I don't think that's going to be simple, and I don't see it as a blocker for the initial release.

**Comment by lahmann** [comment]
@demiankatz this looks great! Thanks! I also agree the book being ready for release. Cross-references might be added later but would take significantly longer to set up now. As we only altered the latex-output in this PR the html-output should not have changed at all (I briefly checked and could not find any differences).
I think for the release we should change the version to 1.1 though and tag it appropriately.

**Comment by demiankatz** [comment]
Thanks, @lahmann, I have merged this and will package a release soon!

**Pull request merged**
