### PR TITLE
Improve code blocks.

### PR DESCRIPTION
**Pull request by demiankatz**

### CODE REVIEW

**Comment by lahmann** [comment]
Thanks Demian, when generating the html files I get warnings, that the code-block "properties" is not known. Did you use any special extension/library?

Edit: as a result the configuration file code in chapter 6 looks different from e.g. chapter 3.

**Comment by lahmann** [comment]
Ah, I found the needed documentation for the available lexers: https://pygments.org/docs/lexers/

So, I went ahead and added some more specific lexers - so only the less-codeblock in chapter 8 is not recognized appropriately but I don't know how to fix that. Therefore there's no highlighting but I think that's acceptable. Do you agree?

If you are ok with the result, I think we can merge this.

**Comment by demiankatz** [comment]
Thanks for the further improvements, @lahmann!

I'm not sure why "properties" isn't recognized (it is listed as a valid option in the documentation you linked to), but in any case, "ini" is a more appropriate choice in the places where you changed it, and the only reason I hadn't used that is because I hadn't been able to find it for some reason. :-)

I'm also not sure why "less" would be a problem, since it is also a documented option, but as you say, if the only problem is a lack of syntax highlighting for those blocks, it is not a major issue.

I'm going to review this one more time, and then merge it if I don't see any problems.

**Comment by demiankatz** [comment]
@lahmann, I'm not seeing problems with the less code blocks when I look at the preview on GitHub, so I imagine support may vary from platform to platform. In any case, I just cleaned up a couple more whitespace issues in PHP blocks and then merged this. Thanks again for the help!

**Pull request merged**
